import { ToolDefinition } from '@/types';

export const TOOL_CATEGORIES = [
  { id: 'dev', name: 'Dev Tools', icon: 'Code2', color: 'from-purple-500 to-pink-500' },
  { id: 'user', name: 'User Tools', icon: 'User', color: 'from-blue-500 to-cyan-500' },
  { id: 'helpful', name: 'Helpful Tools', icon: 'Heart', color: 'from-green-500 to-emerald-500' },
  { id: 'security', name: 'Security', icon: 'Shield', color: 'from-red-500 to-orange-500' },
  { id: 'privacy', name: 'Privacy/OSINT', icon: 'Eye', color: 'from-indigo-500 to-purple-500' },
  { id: 'ai', name: 'AI Tools', icon: 'Sparkles', color: 'from-yellow-500 to-orange-500' },
  { id: 'utility', name: 'Utilities', icon: 'Wrench', color: 'from-teal-500 to-green-500' },
] as const;

export const TOOLS: ToolDefinition[] = [
  // Dev Tools
  {
    id: 'code-formatter',
    name: 'Code Formatter',
    description: 'Format JavaScript, Python, HTML, and CSS code with auto-detection',
    category: 'dev',
    icon: 'FileCode2',
    tags: ['formatter', 'beautify', 'code'],
    path: '/tools/code-formatter',
  },
  {
    id: 'json-converter',
    name: 'JSON ↔ YAML ↔ XML',
    description: 'Convert between JSON, YAML, and XML formats with validation',
    category: 'dev',
    icon: 'FileJson',
    tags: ['converter', 'json', 'yaml', 'xml'],
    path: '/tools/json-converter',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regex patterns with live highlighting and explanations',
    category: 'dev',
    icon: 'Regex',
    tags: ['regex', 'pattern', 'test'],
    path: '/tools/regex-tester',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Mini Postman - test REST APIs with custom headers and body',
    category: 'dev',
    icon: 'Send',
    tags: ['api', 'rest', 'http'],
    path: '/tools/api-tester',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v1, v4, and v7 with bulk options',
    category: 'dev',
    icon: 'Hash',
    tags: ['uuid', 'generator', 'id'],
    path: '/tools/uuid-generator',
  },
  {
    id: 'code-minifier',
    name: 'Code Minifier',
    description: 'Minify JavaScript, HTML, and CSS with compression stats',
    category: 'dev',
    icon: 'Minimize2',
    tags: ['minify', 'compress', 'optimize'],
    path: '/tools/code-minifier',
  },
  {
    id: 'env-manager',
    name: 'Env Variable Manager',
    description: 'Manage, encrypt, and export environment variables',
    category: 'dev',
    icon: 'Settings',
    tags: ['env', 'config', 'security'],
    path: '/tools/env-manager',
  },

  // User Tools
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for text, URLs, WiFi, and contacts',
    category: 'user',
    icon: 'QrCode',
    tags: ['qr', 'generator', 'barcode'],
    path: '/tools/qr-generator',
  },
  {
    id: 'password-checker',
    name: 'Password Strength',
    description: 'Check password strength with entropy scoring and suggestions',
    category: 'user',
    icon: 'KeyRound',
    tags: ['password', 'security', 'checker'],
    path: '/tools/password-checker',
  },
  {
    id: 'fake-data-generator',
    name: 'Fake Data Generator',
    description: 'Generate fake names, addresses, and personal data for testing',
    category: 'user',
    icon: 'Users',
    tags: ['faker', 'data', 'generator'],
    path: '/tools/fake-data-generator',
  },
  {
    id: 'url-shortener',
    name: 'URL Shortener',
    description: 'Shorten URLs with custom aliases and click analytics',
    category: 'user',
    icon: 'Link',
    tags: ['url', 'shortener', 'link'],
    path: '/tools/url-shortener',
  },
  {
    id: 'notepad',
    name: 'Cloud Notepad',
    description: 'Auto-save notepad with Markdown support and cloud sync',
    category: 'user',
    icon: 'FileText',
    tags: ['notepad', 'markdown', 'editor'],
    path: '/tools/notepad',
  },

  // Helpful Tools
  {
    id: 'gpa-calculator',
    name: 'GPA Calculator',
    description: 'Multi-semester GPA calculator with grade scale customization',
    category: 'helpful',
    icon: 'Calculator',
    tags: ['gpa', 'grades', 'education'],
    path: '/tools/gpa-calculator',
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Timer',
    description: 'Focus timer with custom work/break cycles and task tracking',
    category: 'helpful',
    icon: 'Timer',
    tags: ['pomodoro', 'productivity', 'focus'],
    path: '/tools/pomodoro',
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Create professional invoices with custom branding and PDF export',
    category: 'helpful',
    icon: 'Receipt',
    tags: ['invoice', 'billing', 'pdf'],
    path: '/tools/invoice-generator',
  },

  // Security Tools
  {
    id: 'password-leak-checker',
    name: 'Password Leak Checker',
    description: 'Check if your password has been leaked using k-anonymity',
    category: 'security',
    icon: 'ShieldAlert',
    tags: ['password', 'breach', 'security'],
    path: '/tools/password-leak-checker',
  },
  {
    id: 'encryption-tool',
    name: 'Encryption Tool',
    description: 'Encrypt/decrypt text and files with AES, RSA, and Base64',
    category: 'security',
    icon: 'Lock',
    tags: ['encryption', 'aes', 'security'],
    path: '/tools/encryption-tool',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and verify JWT tokens with signature checking',
    category: 'security',
    icon: 'Key',
    tags: ['jwt', 'token', 'auth'],
    path: '/tools/jwt-decoder',
  },
  {
    id: 'ip-lookup',
    name: 'IP Lookup',
    description: 'Get geolocation, ASN, and ISP info for any IP address',
    category: 'security',
    icon: 'MapPin',
    tags: ['ip', 'geolocation', 'lookup'],
    path: '/tools/ip-lookup',
  },

  // Privacy/OSINT Tools
  {
    id: 'username-checker',
    name: 'Username Checker',
    description: 'Check username availability across multiple platforms',
    category: 'privacy',
    icon: 'UserSearch',
    tags: ['username', 'availability', 'social'],
    path: '/tools/username-checker',
  },
  {
    id: 'metadata-remover',
    name: 'Metadata Remover',
    description: 'Remove EXIF and metadata from images and PDFs',
    category: 'privacy',
    icon: 'FileX',
    tags: ['metadata', 'exif', 'privacy'],
    path: '/tools/metadata-remover',
  },
  {
    id: 'whois-lookup',
    name: 'WHOIS Lookup',
    description: 'Get domain ownership and registration information',
    category: 'privacy',
    icon: 'Search',
    tags: ['whois', 'domain', 'lookup'],
    path: '/tools/whois-lookup',
  },

  // AI Tools
  {
    id: 'code-explainer',
    name: 'AI Code Explainer',
    description: 'Get line-by-line explanations of any code snippet',
    category: 'ai',
    icon: 'Brain',
    tags: ['ai', 'code', 'explain'],
    path: '/tools/code-explainer',
  },
  {
    id: 'bug-fixer',
    name: 'AI Bug Fixer',
    description: 'Submit code and errors to get corrected versions',
    category: 'ai',
    icon: 'Bug',
    tags: ['ai', 'debug', 'fix'],
    path: '/tools/bug-fixer',
  },
  {
    id: 'prompt-generator',
    name: 'Prompt Generator',
    description: 'Generate optimized prompts for AI tools and models',
    category: 'ai',
    icon: 'Lightbulb',
    tags: ['ai', 'prompt', 'generator'],
    path: '/tools/prompt-generator',
  },

  // Utility Tools
  {
    id: 'base64-tool',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode text and files to/from Base64',
    category: 'utility',
    icon: 'Binary',
    tags: ['base64', 'encode', 'decode'],
    path: '/tools/base64-tool',
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    description: 'Convert time between multiple timezones with DST awareness',
    category: 'utility',
    icon: 'Clock',
    tags: ['timezone', 'time', 'converter'],
    path: '/tools/timezone-converter',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and generate palettes in HEX, RGB, and HSL',
    category: 'utility',
    icon: 'Palette',
    tags: ['color', 'picker', 'palette'],
    path: '/tools/color-picker',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between units of length, weight, temperature, and more',
    category: 'utility',
    icon: 'ArrowLeftRight',
    tags: ['unit', 'converter', 'measurement'],
    path: '/tools/unit-converter',
  },
];
